version: '3'
networks: 
  nvmanh-network:
    external: true
services:
  mseshop:
    image: mseshop
    container_name: mseshop
    environment:
        - TZ=Asia/Ho_Chi_Minh
    restart: always
    networks:
      - nvmanh-network
    ports:
      - '6868:80'
    build:
      context: .
      dockerfile: MS.eShop.Api/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"