export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const REFRESH_INVENTORY_DATA = "REFRESH_DATA";
export const GET_ALL_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";
export const GET_ALL_FAIL = "GET_ALL_INVENTORY_FAIL";

export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_ALL_EMPLOYEE = "GET_ALL_EMPLOYEE";
export const GET_ALL_PAYMENT_TYPES = "GET_ALL_PAYMENT_TYPES";
