version: '3'
networks: 
  nvmanh-network:
    external: true
services:
  msbaza:
    image: msbaza
    container_name: msbaza
    environment:
        - TZ=Asia/Ho_Chi_Minh
    restart: always
    networks:
      - nvmanh-network
    ports:
      - '6686:80'
    build:
      context: .
      dockerfile: MS.Api/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"