//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Core.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum_DegreeClassification_AverageGood.
        /// </summary>
        public static string Enum_DegreeClassification_AverageGood {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_AverageGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu quỹ hàng năm.
        /// </summary>
        public static string Enum_ExpenditurePlanType_INCREMENT_ANNUAL {
            get {
                return ResourceManager.GetString("Enum_ExpenditurePlanType_INCREMENT_ANNUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu cho sự kiện.
        /// </summary>
        public static string Enum_ExpenditurePlanType_INCREMENT_EVENT {
            get {
                return ResourceManager.GetString("Enum_ExpenditurePlanType_INCREMENT_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu khác.
        /// </summary>
        public static string Enum_ExpenditurePlanType_INCREMENT_OTHER {
            get {
                return ResourceManager.GetString("Enum_ExpenditurePlanType_INCREMENT_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi khác (Ma chay, hiếu hỉ...).
        /// </summary>
        public static string Enum_ExpenditurePlanType_REDUCE_OTHER {
            get {
                return ResourceManager.GetString("Enum_ExpenditurePlanType_REDUCE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi cho sự kiện.
        /// </summary>
        public static string Enum_ExpenditurePlanType_REDURE_EVENT {
            get {
                return ResourceManager.GetString("Enum_ExpenditurePlanType_REDURE_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu từ nguồn khác.
        /// </summary>
        public static string Enum_ExpenditureType_INCREMENT_OTHER {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_INCREMENT_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu theo kế hoạch.
        /// </summary>
        public static string Enum_ExpenditureType_INCREMENT_PLAN {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_INCREMENT_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu từ nguồn ủng hộ của các mạnh thường quân.
        /// </summary>
        public static string Enum_ExpenditureType_INCREMENT_SUPER_RICH {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_INCREMENT_SUPER_RICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi ốm đau, nghỉ bệnh.
        /// </summary>
        public static string Enum_ExpenditureType_REDUCE_MEDICAL {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_REDUCE_MEDICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi khác.
        /// </summary>
        public static string Enum_ExpenditureType_REDUCE_OTHER {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_REDUCE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi đám tang/ đám hiểu.
        /// </summary>
        public static string Enum_ExpenditureType_REDURE_FUNERAL {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_REDURE_FUNERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi theo kế hoạch.
        /// </summary>
        public static string Enum_ExpenditureType_REDURE_PLAN {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_REDURE_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi đám cưới thành viên.
        /// </summary>
        public static string Enum_ExpenditureType_REDURE_WEDDING {
            get {
                return ResourceManager.GetString("Enum_ExpenditureType_REDURE_WEDDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn.
        /// </summary>
        public static string Enum_TimeRange_Custom {
            get {
                return ResourceManager.GetString("Enum_TimeRange_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng này.
        /// </summary>
        public static string Enum_TimeRange_ThisMonth {
            get {
                return ResourceManager.GetString("Enum_TimeRange_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý này.
        /// </summary>
        public static string Enum_TimeRange_ThisQuarter {
            get {
                return ResourceManager.GetString("Enum_TimeRange_ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần này.
        /// </summary>
        public static string Enum_TimeRange_ThisWeek {
            get {
                return ResourceManager.GetString("Enum_TimeRange_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm nay.
        /// </summary>
        public static string Enum_TimeRange_ThisYear {
            get {
                return ResourceManager.GetString("Enum_TimeRange_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Enum_TimeRange_Today {
            get {
                return ResourceManager.GetString("Enum_TimeRange_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm qua.
        /// </summary>
        public static string Enum_TimeRange_Yesterday {
            get {
                return ResourceManager.GetString("Enum_TimeRange_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 ngày.
        /// </summary>
        public static string Enum_VIPOptions_HALF_MONTH {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_HALF_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 tháng.
        /// </summary>
        public static string Enum_VIPOptions_HALF_YEAR {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_HALF_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vĩnh viễn.
        /// </summary>
        public static string Enum_VIPOptions_NO_LIMITTED {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_NO_LIMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tháng.
        /// </summary>
        public static string Enum_VIPOptions_ONE_MONTH {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_ONE_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tuần.
        /// </summary>
        public static string Enum_VIPOptions_ONE_WEEK {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_ONE_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 năm.
        /// </summary>
        public static string Enum_VIPOptions_ONE_YEAR {
            get {
                return ResourceManager.GetString("Enum_VIPOptions_ONE_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Enum_WorkStatus_OTHER {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nghỉ việc.
        /// </summary>
        public static string Enum_WorkStatus_STOPPING {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string Enum_WorkStatus_WORKING {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_WORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ Quản trị viên để được trợ giúp.
        /// </summary>
        public static string Exception_Message_General {
            get {
                return ResourceManager.GetString("Exception_Message_General", resourceCulture);
            }
        }
    }
}
